"""Add coordinates to interaction

Revision ID: a4ed36d8c596
Revises: e1d5016e1f23
Create Date: 2026-08-27 23:04:10.248310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4ed36d8c596'
down_revision: Union[str, Sequence[str], None] = 'e1d5016e1f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('worker_x', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('worker_y', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('worker_z', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('machine_x', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('machine_y', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('machine_z', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('direction_worker', sa.Integer(), nullable=True))
    op.add_column('interactions', sa.Column('direction_machine', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'direction_machine')
    op.drop_column('interactions', 'direction_worker')
    op.drop_column('interactions', 'machine_z')
    op.drop_column('interactions', 'machine_y')
    op.drop_column('interactions', 'machine_x')
    op.drop_column('interactions', 'worker_z')
    op.drop_column('interactions', 'worker_y')
    op.drop_column('interactions', 'worker_x')
    # ### end Alembic commands ###
